"$schema" = 'https://starship.rs/config-schema.json'

# Palette definition (Oxocarbon Dark)
# Purple (Primary Accent): #be95ff
# Pink / Magenta (Accent / Error): #ee5396
# Dark Grey (Base): #161616
# Mid Grey (Subtle): #262626
# Light Grey (Foreground text): #dde1e6

format = """
$directory\
$git_branch\
$git_status\
$time\
\n$character"""

[directory]
style = "fg:#161616 bg:#be95ff"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "fg:#be95ff bg:#262626"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#be95ff bg:#262626"
deleted = "✘ "    
untracked = ""  
modified = "!"  
stashed = "󰏗"   
renamed = "»"
format = '[([$all_status$ahead_behind ]($style))]($style)'

[time]
disabled = false
time_format = "%R" 
style = "fg:#dde1e6 bg:#161616"
format = '[  $time ]($style)'

[character]
success_symbol = "[ ❯](bold #be95ff)"
error_symbol = "[ ❯](bold #ee5396)"
