unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -g prefix C-f
set -g mouse on
set-option -g status-position bottom
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# Move current window left/right in the window list
bind-key -r H swap-window -t :-1 \; select-window -t :-1
bind-key -r L swap-window -t :+1 \; select-window -t :+1
# Open new splits/windows in the current pane's directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.config/tmux/plugins/tpm/tpm'
